spring:
  datasource:
    url: jdbc:h2:mem:test
  h2.console.enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.search.backend:
        uris: http://localhost:9200
        username: elastic
        password: changeme
logging:
  level:
    com.monkeydp.sample.springboot.hibernate.search: info
    jdbc:
      sqlonly: fatal
      resultsettable: info
      sqltiming: info
      audit: fatal
      resultset: fatal
      connection: fatal
log4jdbc:
  dump:
    sql:
      addsemicolon: true
      maxlinelength: 0
  trim:
    sql:
      extrablanklines: false
